# Generated by Django 5.2 on 2026-02-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0005_rename_user_id_instructor_user'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorPayoutMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('momo', 'MoMo'), ('vnpay', 'VNPay')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, help_text="VD: 'Tài khoản VCB cá nhân'", max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wallet_phone', models.CharField(blank=True, help_text='Số điện thoại ví điện tử', max_length=20, null=True)),
                ('masked_account', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='instructors.instructor')),
            ],
            options={
                'db_table': 'InstructorPayoutMethods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, help_text="Tên hiển thị ví dụ: 'Thẻ cá nhân', 'Ví MoMo công ty'", max_length=100, null=True)),
                ('gateway_token', models.CharField(blank=True, help_text='Token từ payment gateway (không phải số thẻ thô)', max_length=512, null=True)),
                ('masked_account', models.CharField(blank=True, help_text='VD: ****6789 hoặc 09*****23', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='users.user')),
            ],
            options={
                'db_table': 'UserPaymentMethods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
