# Generated by Django 5.2 on 2026-02-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('registration_forms', '0001_initial'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registration_forms.registrationform'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='users.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.user'),
        ),
        migrations.AddField(
            model_name='applicationresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='registration_forms.formquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationresponse',
            unique_together={('application', 'question')},
        ),
    ]
