# Generated by Django 5.2 on 2026-02-19 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('enrollments', '0007_enrollment_payment'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_code', models.CharField(default=uuid.uuid4, help_text='Unique code for public certificate verification', max_length=36, unique=True)),
                ('certificate_url', models.CharField(blank=True, help_text='Cloudinary URL of the generated certificate PDF/image', max_length=500, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_record', to='enrollments.enrollment')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.user')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_certificate')],
            },
        ),
    ]
