# Generated by Django 5.2 on 2026-02-23 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
