# Generated by Django 5.2 on 2026-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_status'),
        ('categories', '0003_rename_category_id_category_id'),
    ]

    operations = [
    ]
