# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
    ]
