# Generated by Django 5.2 on 2026-06-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_add_other_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
