import type { HomeSchemaV2 } from "./schema"

export const HARDCODED_BACKUP_HOME_SCHEMA: HomeSchemaV2 = {
  version: 2,
  meta: {
    updated_at: "2026-03-28T09:45:22.970Z",
    updated_by: 0,
  },
  sections: [
    {
      id: "legacy_component_1774691118511_ik8o9y",
      type: "legacy_component",
      enabled: true,
      order: 1,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "HeroSection" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_bkmygl",
      type: "legacy_component",
      enabled: true,
      order: 2,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "TrustedCompanies" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_5w88hy",
      type: "legacy_component",
      enabled: true,
      order: 3,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "FeaturesSection" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_7ek1pl",
      type: "legacy_component",
      enabled: true,
      order: 4,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "Categories" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_a0vyrj",
      type: "legacy_component",
      enabled: true,
      order: 5,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "FeaturedCourses" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_kmgekg",
      type: "legacy_component",
      enabled: true,
      order: 6,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "LearningGoals" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_nbubal",
      type: "legacy_component",
      enabled: true,
      order: 7,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "TrendingCourses" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_qzuag5",
      type: "legacy_component",
      enabled: true,
      order: 8,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "PopularSkills" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_2chfas",
      type: "legacy_component",
      enabled: true,
      order: 9,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "TestimonialsSection" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_tnogbs",
      type: "legacy_component",
      enabled: true,
      order: 10,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "StatsSection" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_0o1qwk",
      type: "legacy_component",
      enabled: true,
      order: 11,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "InstructorPromo" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
    {
      id: "legacy_component_1774691118511_jxcp1w",
      type: "legacy_component",
      enabled: true,
      order: 12,
      layout: { container: "default", spacing_top: "md", spacing_bottom: "md", background: "none" },
      content: {},
      data_source: { component: "NewsletterSection" },
      display_rules: { devices: ["mobile", "desktop"], audience: "all" },
    },
  ],
}
