# Generated by Django 5.2 on 2025-08-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0005_alter_admin_user_id'),
        ('supports', '0001_initial'),
        ('users', '0002_alter_user_status_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_replies', to='admins.admin')),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='supports.support')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_replies', to='users.user')),
            ],
        ),
    ]
