# Generated by Django 5.2 on 2026-02-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_rename_admin_id_admin_id_rename_user_id_admin_user'),
        ('support_replies', '0002_rename_admin_id_supportreply_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportreply',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_replies', to='admins.admin'),
        ),
    ]
