# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_replies', '0003_alter_supportreply_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportreply',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='supportreply',
            table='SupportReplies',
        ),
    ]
