# Generated by Django 5.2 on 2026-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_remove_enrollment_unique_enrollment_and_more'),
        ('enrollments', '0005_alter_enrollment_created_at'),
    ]

    operations = [
    ]
