# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_attachments', '0003_rename_attachment_id_lessonattachment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonattachment',
            options={'ordering': ['-created_at']},
        ),
    ]
