# Generated by Django 5.2 on 2026-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách mục tiêu học tập'),
        ),
        migrations.AddField(
            model_name='course',
            name='promotional_video',
            field=models.CharField(blank=True, help_text='URL video giới thiệu', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách đối tượng mục tiêu'),
        ),
    ]
