# Generated by Django 6.0.4 on 2026-05-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_prerequisites_course_skills_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='skills_taught',
        ),
    ]
