# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_searchevent_user_id_3af5f0_idx_searchevent_user_id_97b967_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchevent',
            options={'ordering': ['-created_at']},
        ),
    ]
