# Generated by Django 6.0.4 on 2026-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettercampaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='audience',
            field=models.CharField(choices=[('subscribers', 'Subscribers'), ('all_users', 'All users'), ('instructors', 'Instructors'), ('students', 'Students')], default='subscribers', max_length=20),
        ),
    ]
