# Generated by Django 5.2 on 2026-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comments', '0002_rename_created_date_forumcomment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='forumcomment',
            old_name='parent_comment',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='forumcomment',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='forumcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
