# Generated by Django 5.2 on 2026-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_rename_created_date_forum_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='forum_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='user_id',
            new_name='user',
        ),
    ]
