# Generated by Django 5.2 on 2026-02-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category_alter_course_instructor_and_more'),
        ('forums', '0003_rename_course_id_forum_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums_course', to='courses.course'),
        ),
    ]
