# Generated by Django 5.2 on 2026-02-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('reviews', '0002_rename_review_date_review_created_at_and_more'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to='users.user'),
        ),
    ]
