# Generated by Django 5.2 on 2026-02-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('reviews', '0003_alter_review_options_rename_review_id_review_id_and_more'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_course', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to='users.user'),
            preserve_default=False,
        ),
    ]
