# Generated by Django 5.2 on 2026-02-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessoncomment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='lessoncomment',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='lessoncomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
