# Generated by Django 6.0.4 on 2026-06-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_comments', '0003_alter_lessoncomment_parent_comment'),
        ('users', '0008_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_lesson_comments', to='users.user'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=10),
        ),
    ]
