# Generated by Django 6.0.4 on 2026-06-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_comments', '0004_lessoncomment_deleted_at_lessoncomment_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncomment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='lessoncomment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lessoncomment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='lessoncomment',
            name='status',
        ),
    ]
