# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_comments', '0006_lessoncomment_deleted_at_lessoncomment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='lessoncomment',
            table='LessonComments',
        ),
    ]
