# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_levels', '0004_instructorlevel_min_plan_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorlevel',
            options={'ordering': ['-created_at']},
        ),
    ]
