# Generated by Django 5.2 on 2026-02-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodules', '0004_rename_module_id_coursemodule_id_and_more'),
        ('lessons', '0003_rename_lesson_id_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='coursemodule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='coursemodules.coursemodule'),
            preserve_default=False,
        ),
    ]
