# Generated by Django 5.2 on 2026-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_rename_created_date_promotion_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='promotion_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
