# Generated by Django 6.0.4 on 2026-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_rename_admin_id_promotion_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
