# Generated by Django 5.2 on 2026-03-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('system', 'System')], default='direct', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='users.user')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_conversations', to='users.user')),
            ],
            options={
                'db_table': 'ChatConversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('system', 'System')], default='text', max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('edited', 'Edited'), ('revoked', 'Revoked'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='realtime.conversation')),
                ('forwarded_from_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='realtime.conversation')),
                ('forwarded_from_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_copies', to='realtime.message')),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='realtime.message')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_revoked', to='users.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages_sent', to='users.user')),
            ],
            options={
                'db_table': 'ChatConversationMessages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('notification_level', models.CharField(choices=[('all', 'All'), ('mentions', 'Mentions'), ('mute', 'Mute')], default='all', max_length=20)),
                ('can_send_message', models.BooleanField(default=True)),
                ('can_add_members', models.BooleanField(default=False)),
                ('can_change_group_info', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='realtime.conversation')),
                ('joined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_participants_joined', to='users.user')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_participants_removed', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversation_memberships', to='users.user')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_by_participants', to='realtime.message')),
            ],
            options={
                'db_table': 'ChatConversationParticipants',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_conversations', to='realtime.message'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('cloudinary', 'Cloudinary'), ('other', 'Other')], default='local', max_length=20)),
                ('file_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='realtime.message')),
            ],
            options={
                'db_table': 'ChatMessageAttachments',
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_states', to='realtime.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_delivery_states', to='users.user')),
            ],
            options={
                'db_table': 'ChatMessageDeliveryStates',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reaction', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='realtime.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='users.user')),
            ],
            options={
                'db_table': 'ChatMessageReactions',
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='realtime.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='realtime.message')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages_created', to='users.user')),
            ],
            options={
                'db_table': 'ChatPinnedMessages',
            },
        ),
        migrations.CreateModel(
            name='UserChatBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_chat_users', to='users.user')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_chat_users', to='users.user')),
            ],
            options={
                'db_table': 'ChatUserBlocks',
            },
        ),
        migrations.CreateModel(
            name='UserChatPrivacy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allow_direct_messages', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_group_invites', models.BooleanField(default=True)),
                ('read_receipts_enabled', models.BooleanField(default=True)),
                ('last_seen_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_privacy_settings', to='users.user')),
            ],
            options={
                'db_table': 'ChatUserPrivacySettings',
            },
        ),
        migrations.CreateModel(
            name='ChatSystemEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_system_events', to='users.user')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='realtime.conversation')),
            ],
            options={
                'db_table': 'ChatSystemEvents',
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='ChatSystemE_convers_0703f6_idx'), models.Index(fields=['event_type', 'created_at'], name='ChatSystemE_event_t_b42a1d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='ChatConvers_convers_f71b04_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='ChatConvers_sender__0b16d5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to_message'], name='ChatConvers_reply_t_592069_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'is_active'], name='ChatConvers_user_id_5b6709_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'is_active'], name='ChatConvers_convers_826e06_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_chat_participant_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type', 'updated_at'], name='ChatConvers_type_b65e60_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='ChatConvers_last_me_5c7fff_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='ChatMessage_message_ab1c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['kind', 'created_at'], name='ChatMessage_kind_53cb11_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliverystate',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_delivery_state_per_message_user'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'reaction'), name='unique_reaction_per_message_user'),
        ),
        migrations.AddConstraint(
            model_name='pinnedmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'message', 'is_active'), name='unique_active_pin_per_message'),
        ),
        migrations.AddConstraint(
            model_name='userchatblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_chat_block_relationship'),
        ),
    ]
