# Generated by Django 5.2 on 2026-02-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodules', '0004_rename_module_id_coursemodule_id_and_more'),
        ('courses', '0004_rename_category_id_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.course'),
        ),
    ]
