# Generated by Django 5.2 on 2026-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0004_alter_qna_course_alter_qna_lesson_alter_qna_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qna',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='qna',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
