# Generated by Django 5.2 on 2026-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0002_alter_support_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='support',
            old_name='support_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='support',
            old_name='user_id',
            new_name='user',
        ),
    ]
