# Generated by Django 5.2 on 2026-06-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_certificate_default_true'),
        ('supports', '0004_alter_support_priority_alter_support_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='courses.course'),
        ),
        migrations.AddField(
            model_name='support',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='support',
            name='resolution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='support',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'general'), ('course_deletion_request', 'course_deletion_request'), ('refund', 'refund'), ('copyright', 'copyright'), ('other', 'other')], default='general', max_length=32),
        ),
    ]
