# Generated by Django 6.0.4 on 2026-06-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_remove_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('review', 'review'), ('question', 'question'), ('answer', 'answer'), ('blog_post', 'blog_post'), ('blog_comment', 'blog_comment'), ('lesson_comment', 'lesson_comment'), ('course', 'course'), ('message', 'message')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Nội dung phản cảm'), ('harassment', 'Quấy rối / bắt nạt'), ('copyright', 'Vi phạm bản quyền'), ('misinformation', 'Thông tin sai lệch'), ('other', 'Khác')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reviewing', 'reviewing'), ('resolved', 'resolved'), ('dismissed', 'dismissed')], default='pending', max_length=12)),
                ('action_taken', models.CharField(blank=True, max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to='users.user')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to='users.user')),
            ],
            options={
                'db_table': 'Reports',
                'indexes': [models.Index(fields=['target_type', 'target_id', 'status'], name='Reports_target__5dd8ac_idx'), models.Index(fields=['reporter', 'target_type', 'target_id'], name='Reports_reporte_110329_idx')],
            },
        ),
    ]
