# Generated by Django 5.2 on 2026-06-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_certificate_default_true'),
        ('instructor_earnings', '0013_backfill_retail_legacy_snapshot'),
        ('instructors', '0008_instructor_level_locked'),
        ('lessons', '0006_alter_lesson_content_type_add_code'),
        ('reports', '0002_alter_report_options'),
        ('users', '0010_user_pending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('review', 'review'), ('question', 'question'), ('answer', 'answer'), ('blog_post', 'blog_post'), ('blog_comment', 'blog_comment'), ('lesson_comment', 'lesson_comment'), ('lesson', 'lesson'), ('course', 'course'), ('message', 'message')], max_length=20),
        ),
        migrations.CreateModel(
            name='CopyrightCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('review', 'review'), ('question', 'question'), ('answer', 'answer'), ('blog_post', 'blog_post'), ('blog_comment', 'blog_comment'), ('lesson_comment', 'lesson_comment'), ('lesson', 'lesson'), ('course', 'course'), ('message', 'message')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('status', models.CharField(choices=[('under_review', 'under_review'), ('needs_reporter_info', 'needs_reporter_info'), ('awaiting_instructor_response', 'awaiting_instructor_response'), ('instructor_responded', 'instructor_responded'), ('awaiting_instructor_fix', 'awaiting_instructor_fix'), ('insufficient_info', 'insufficient_info'), ('resolved_valid', 'resolved_valid'), ('resolved_rejected', 'resolved_rejected'), ('takedown', 'takedown'), ('restored', 'restored'), ('escalated_legal', 'escalated_legal')], default='under_review', max_length=40)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('confirmed', 'confirmed'), ('legal', 'legal')], default='low', max_length=20)),
                ('content_action', models.CharField(choices=[('none', 'none'), ('sale_suspended', 'sale_suspended'), ('lesson_hidden', 'lesson_hidden'), ('access_suspended', 'access_suspended'), ('takedown', 'takedown'), ('restored', 'restored')], default='none', max_length=30)),
                ('financial_action', models.CharField(choices=[('none', 'none'), ('hold', 'hold'), ('released', 'released'), ('adjusted', 'adjusted'), ('manual_follow_up', 'manual_follow_up')], default='none', max_length=30)),
                ('reporter_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('instructor_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('manual_follow_up', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_cases', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_cases_created', to='users.user')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_cases', to='instructors.instructor')),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_cases_last_actioned', to='users.user')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_cases', to='lessons.lesson')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_cases_resolved', to='users.user')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_case_sources', to='reports.report')),
            ],
            options={
                'db_table': 'CopyrightCases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightCaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('reporter', 'reporter'), ('instructor', 'instructor'), ('admin', 'admin'), ('system', 'system')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('response_type', models.CharField(blank=True, max_length=40)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('admin_only', 'admin_only'), ('shared_with_reporter', 'shared_with_reporter'), ('shared_with_instructor', 'shared_with_instructor')], default='admin_only', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_case_messages', to='users.user')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.copyrightcase')),
            ],
            options={
                'db_table': 'CopyrightCaseMessages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorEarningHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('released', 'released'), ('adjusted', 'adjusted')], default='active', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_holds', to='reports.copyrightcase')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_earning_holds', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_earning_holds', to='users.user')),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_holds', to='instructor_earnings.instructorearning')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_earning_holds', to='instructors.instructor')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_earning_holds', to='users.user')),
            ],
            options={
                'db_table': 'InstructorEarningHolds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='copyrightcase',
            index=models.Index(fields=['target_type', 'target_id', 'status'], name='CopyrightCa_target__76bda0_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightcase',
            index=models.Index(fields=['instructor', 'status'], name='CopyrightCa_instruc_675b40_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightcase',
            index=models.Index(fields=['created_by', 'status'], name='CopyrightCa_created_51678c_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightcasemessage',
            index=models.Index(fields=['case', 'created_at'], name='CopyrightCa_case_id_8fb0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightcasemessage',
            index=models.Index(fields=['actor', 'actor_role'], name='CopyrightCa_actor_i_965d45_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearninghold',
            index=models.Index(fields=['status', 'course', 'instructor'], name='InstructorE_status_0f9da4_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearninghold',
            index=models.Index(fields=['earning', 'status'], name='InstructorE_earning_230cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearninghold',
            index=models.Index(fields=['case', 'status'], name='InstructorE_case_id_934348_idx'),
        ),
        migrations.AddConstraint(
            model_name='instructorearninghold',
            constraint=models.UniqueConstraint(fields=('case', 'earning'), name='unique_hold_per_case_earning'),
        ),
    ]
