# Generated by Django 5.2 on 2026-06-15 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_instructor_level_locked'),
        ('reports', '0004_report_metadata_report_attachments'),
        ('users', '0010_user_pending_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('severity', models.CharField(default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strikes', to='users.user')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_strikes', to='instructors.instructor')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_strikes', to='users.user')),
                ('source_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes', to='reports.copyrightcase')),
            ],
            options={
                'db_table': 'InstructorStrikes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'revoked_at'], name='InstructorS_instruc_e63a7f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('source_case',), name='unique_active_strike_per_case')],
            },
        ),
    ]
