# Generated by Django 5.2 on 2026-06-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_instructorstrike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyrightcase',
            name='instructor_deadline_at',
        ),
        migrations.RemoveField(
            model_name='copyrightcase',
            name='reporter_deadline_at',
        ),
        migrations.AlterField(
            model_name='copyrightcase',
            name='status',
            field=models.CharField(choices=[('under_review', 'under_review'), ('insufficient_info', 'insufficient_info'), ('resolved_rejected', 'resolved_rejected'), ('takedown', 'takedown'), ('restored', 'restored'), ('escalated_legal', 'escalated_legal')], default='under_review', max_length=40),
        ),
        migrations.AlterField(
            model_name='copyrightcasemessage',
            name='visibility',
            field=models.CharField(choices=[('admin_only', 'admin_only')], default='admin_only', max_length=30),
        ),
    ]
