# Generated by Django 5.2 on 2025-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0006_remove_payment_details_is_refunded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved - waiting for refund'), ('success', 'Refunded successfully'), ('rejected', 'Rejected'), ('failed', 'Refund failed')], default='pending', max_length=20),
        ),
    ]
