# Generated by Django 5.2 on 2026-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0009_rename_course_id_payment_details_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved - waiting for refund'), ('success', 'Refunded successfully'), ('rejected', 'Rejected'), ('failed', 'Refund failed'), ('cancelled', 'Cancelled by user')], default='pending', max_length=20),
        ),
    ]
