# Generated by Django 5.2 on 2026-03-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0011_refund_workflow_metadata'),
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='processed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='processed_payment_details',
                to='users.user',
            ),
        ),
    ]
