# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0013_payment_details_processed_by_admin_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_details',
            options={'ordering': ['-created_at']},
        ),
    ]
