# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_votes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answervote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questionvote',
            options={'ordering': ['-created_at']},
        ),
    ]
