# Generated by Django 5.2 on 2026-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna_answers', '0002_rename_answered_date_qnaanswer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnaanswer',
            old_name='answer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='qnaanswer',
            old_name='qna_id',
            new_name='qna',
        ),
        migrations.RenameField(
            model_name='qnaanswer',
            old_name='user_id',
            new_name='user',
        ),
    ]
