# Generated by Django 6.0.4 on 2026-05-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('duplicate', 'duplicate')], default='open', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('last_report_reason', models.TextField(blank=True, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_author', to='users.user')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_questions', to='users.user')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
    ]
