# Generated by Django 6.0.4 on 2026-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('duplicate', 'duplicate'), ('hidden', 'hidden')], default='open', max_length=20),
        ),
    ]
