# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems_settings', '0003_rename_admin_id_systemssetting_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemssetting',
            options={'ordering': ['-created_at']},
        ),
    ]
