# Generated by Django 6.0.4 on 2026-06-14 07:50

import systems_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems_settings', '0006_remove_legacy_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='legal_policies',
            field=models.JSONField(default=systems_settings.models.default_legal_policies),
        ),
    ]
