# Generated by Django 5.2 on 2026-04-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_course_content_changed_since_publish'),
        ('lessons', '0006_alter_lesson_content_type_add_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('transcript', 'Transcript'), ('attachment', 'Attachment')], max_length=20)),
                ('source_object_id', models.PositiveIntegerField()),
                ('source_group_key', models.CharField(max_length=255)),
                ('language_code', models.CharField(default='und', max_length=16)),
                ('visibility', models.CharField(choices=[('published', 'Published'), ('instructor_preview', 'Instructor Preview')], default='published', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('citation_label', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['chunk_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('lesson', 'Lesson'), ('course', 'Course'), ('document', 'Document')], default='document', max_length=16)),
                ('trigger_source', models.CharField(choices=[('transcript_published', 'Transcript Published'), ('transcript_updated', 'Transcript Updated'), ('attachment_created', 'Attachment Created'), ('attachment_updated', 'Attachment Updated'), ('manual', 'Manual'), ('lesson_published', 'Lesson Published')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('source_type', models.CharField(choices=[('transcript', 'Transcript'), ('attachment', 'Attachment')], max_length=20)),
                ('source_object_id', models.PositiveIntegerField()),
                ('source_group_key', models.CharField(blank=True, default='', max_length=255)),
                ('visibility', models.CharField(choices=[('published', 'Published'), ('instructor_preview', 'Instructor Preview')], default='published', max_length=24)),
                ('language_code', models.CharField(blank=True, default='', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_jobs', to='courses.course')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='knowledge.knowledgedocument')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_jobs', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['course', 'status', 'visibility'], name='knowledge_k_course__2788e3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['lesson', 'status', 'visibility'], name='knowledge_k_lesson__21a07e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source_type', 'source_object_id'], name='knowledge_k_source__182b81_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source_group_key', 'version'], name='knowledge_k_source__8d9698_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_knowledge_chunk_index'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestjob',
            index=models.Index(fields=['status', 'created_at'], name='knowledge_k_status_bcc264_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestjob',
            index=models.Index(fields=['source_type', 'source_object_id', 'visibility'], name='knowledge_k_source__1dffff_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestjob',
            index=models.Index(fields=['course', 'lesson'], name='knowledge_k_course__a85479_idx'),
        ),
    ]
