# Generated by Django 5.2 on 2026-04-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_content_changed_since_publish"),
        ("knowledge", "0001_initial"),
        ("lessons", "0006_alter_lesson_content_type_add_code"),
        ("users", "0006_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=16)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_conversations", to="courses.course")),
                ("lesson", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="assistant_conversations", to="lessons.lesson")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_conversations", to="users.user")),
            ],
            options={
                "ordering": ["-last_message_at", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("system", "System"), ("user", "User"), ("assistant", "Assistant")], max_length=16)),
                ("content", models.TextField()),
                ("citations_json", models.JSONField(blank=True, default=list)),
                ("retrieval_context_json", models.JSONField(blank=True, default=dict)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="knowledge.assistantconversation")),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(fields=["user", "course", "lesson", "status"], name="kn_asstconv_user_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(fields=["course", "lesson", "status"], name="kn_asstconv_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(fields=["conversation", "created_at"], name="kn_asstmsg_conv_idx"),
        ),
    ]
