# Generated by Django 6.0.4 on 2026-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_rename_admin_id_admin_id_rename_user_id_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
