# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_add_is_super_admin_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['-created_at']},
        ),
    ]
