# Generated by Django 5.2 on 2026-02-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_added_date_cart_created_at_and_more'),
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('promotions', '0003_rename_admin_id_promotion_admin_and_more'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_cart',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='promotion_id',
            new_name='promotion',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='course_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_course', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_cart'),
        ),
    ]
