# Generated by Django 5.2 on 2026-02-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('enrollments', '0004_remove_enrollment_unique_enrollment_and_more'),
        ('learning_progress', '0003_learningprogress_deleted_at_and_more'),
        ('lessons', '0003_rename_lesson_id_lesson_id_and_more'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learningprogress',
            name='unique_learning_progress',
        ),
        migrations.RenameField(
            model_name='learningprogress',
            old_name='progress_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='learningprogress',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='learningprogress',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='learningprogress',
            name='enrollment_id',
        ),
        migrations.RemoveField(
            model_name='learningprogress',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_lesson', to='lessons.lesson'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_learning_progress'),
        ),
    ]
