# Generated by Django 5.2 on 2026-02-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('enrollments', '0004_remove_enrollment_unique_enrollment_and_more'),
        ('learning_progress', '0005_remove_learningprogress_unique_learning_progress_and_more'),
        ('lessons', '0003_rename_lesson_id_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningprogress',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_course', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='enrollment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='enrollments.enrollment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_lesson', to='lessons.lesson'),
            preserve_default=False,
        ),
    ]
