# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_progress', '0006_alter_learningprogress_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningprogress',
            options={'ordering': ['-created_at']},
        ),
    ]
