# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'ordering': ['-created_at']},
        ),
    ]
