# Generated by Django 5.2 on 2026-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
