# Generated by Django 5.2 on 2026-02-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_gateway_response'),
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('course_purchase', 'Course Purchase'), ('subscription', 'Subscription')], default='course_purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscription_plans.subscriptionplan'),
        ),
    ]
