# Generated by Django 5.2 on 2026-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_payment_type_payment_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ipn_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
