# Generated by Django 6.0.4 on 2026-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_ipn_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='momo_request_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
