"""
Django settings for course project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""



import dj_database_url
from pathlib import Path
import os
from urllib.parse import urlparse
from corsheaders.defaults import default_headers

BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env_file(env_file_path):
    if not env_file_path.exists():
        return



    force_override_keys = {
        'LEARNING_PATH_PROVIDER',
        'LEARNING_PATH_FORCE_GEMINI',
        'LEARNING_PATH_GEMINI_MAX_ATTEMPTS',
        'LEARNING_PATH_GEMINI_CIRCUIT_THRESHOLD',
        'LEARNING_PATH_GEMINI_CIRCUIT_COOLDOWN_SECONDS',
        'GEMINI_API_KEY',
        'GEMINI_MODEL',
        'GEMINI_TIMEOUT_SECONDS',
    }

    for raw_line in env_file_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            if key in force_override_keys:
                os.environ[key] = value
            else:
                os.environ.setdefault(key, value)


load_local_env_file(BASE_DIR / '.env')






SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-&fdfpm3&397v^3-cay1lhfg$5ktshko79(^56-vu&)zx29eclj'
)


ASGI_APPLICATION = "config.asgi.application"
DEBUG = os.getenv('DEBUG', 'False') == 'True'

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


extra_hosts = os.getenv('ALLOWED_HOSTS', '')
if extra_hosts:
    ALLOWED_HOSTS.extend(extra_hosts.split(','))
def get_env(key, default=None, required=False):
    value = os.getenv(key, default)
    if not value:
        print(f"⚠️ Warning: {key} not set. Please set it in your environment variables.")
        if required:
            raise EnvironmentError(f"❌ {key} is required but not set.")
    return value





REDIS_URL = get_env("REDIS_URL", default="")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }




CLOUDINARY_CLOUD_NAME = get_env("CLOUDINARY_CLOUD_NAME", default="dqzopvk2t")
CLOUDINARY_API_KEY = get_env("CLOUDINARY_API_KEY", default="791785722646617")
CLOUDINARY_API_SECRET = get_env("CLOUDINARY_API_SECRET", default="eYOL6HTUSbXlZNdtAyY4chQlgrk")
VIDEO_SIGNED_URL_TTL_SECONDS = int(get_env("VIDEO_SIGNED_URL_TTL_SECONDS", default="1800"))





REFUND_DAYS = 7
VNPAY_HASH_SECRET_KEY = os.getenv('VNPAY_HASH_SECRET_KEY', 'T84Y15XCZM36DT7YQHRHN7RT2V2JBA6T')






VNPAY_REFUND_URL = "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
VNPAY_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_TMN_CODE = os.getenv('VNPAY_TMN_CODE', 'BDF9QK1Y')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "dukolc78@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "ahbv oxuf ssvx klkb")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", f"Online Course <{EMAIL_HOST_USER}>")


FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000").rstrip("/")
PAYMENT_RESULT_URL = os.getenv("PAYMENT_RESULT_URL", f"{FRONTEND_URL}/payment/result").rstrip("/")
VNPAY_FE_RETURN_URL = os.getenv("VNPAY_FE_RETURN_URL", PAYMENT_RESULT_URL).rstrip("/")
MOMO_FE_RETURN_URL = os.getenv("MOMO_FE_RETURN_URL", PAYMENT_RESULT_URL).rstrip("/")
NGROK_URL = os.getenv("NGROK_URL", "").rstrip("/")
BACKEND_PUBLIC_URL = os.getenv("BACKEND_PUBLIC_URL", "").rstrip()
if NGROK_URL:
    BACKEND_PUBLIC_URL = NGROK_URL
if not BACKEND_PUBLIC_URL:
    BACKEND_PUBLIC_URL = "https://course-1-zelz.onrender.com"
if not BACKEND_PUBLIC_URL and RENDER_EXTERNAL_HOSTNAME:
    BACKEND_PUBLIC_URL = f"https://{RENDER_EXTERNAL_HOSTNAME}"
for candidate_url in (FRONTEND_URL, PAYMENT_RESULT_URL, VNPAY_FE_RETURN_URL, MOMO_FE_RETURN_URL, NGROK_URL, BACKEND_PUBLIC_URL):
    if not candidate_url:
        continue
    parsed = urlparse(candidate_url)
    host = parsed.hostname
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)
EMAIL_VERIFICATION_TOKEN_MINUTES = int(os.getenv("EMAIL_VERIFICATION_TOKEN_MINUTES", "30"))
EMAIL_VERIFICATION_TOKEN_MINUTES = max(15, min(30, EMAIL_VERIFICATION_TOKEN_MINUTES))
GOOGLE_OAUTH_CLIENT_IDS = [
    client_id.strip()
    for client_id in os.getenv(
        "GOOGLE_OAUTH_CLIENT_IDS",
        "769246063466-q50orj7aqn9rshcdaiu2m03d1lc8fq46.apps.googleusercontent.com",
    ).split(",")
    if client_id.strip()
]

VNPAY_RETURN_URL = os.getenv(
    "VNPAY_RETURN_URL",
    f"{BACKEND_PUBLIC_URL}/api/vnpay/payment-return/" if BACKEND_PUBLIC_URL else "http://127.0.0.1:8000/api/vnpay/payment-return/",
)

MOMO_PARTNER_CODE = os.getenv("MOMO_PARTNER_CODE", "MOMO")

MOMO_ACCESS_KEY = os.getenv("MOMO_ACCESS_KEY", "F8BBA842ECF85")


MOMO_SECRET_KEY = os.getenv("MOMO_SECRET_KEY", "K951B6PE1waDMi640xX08PD3vg6EkVlz")

MOMO_CREATE_URL = os.getenv("MOMO_CREATE_URL", "https://test-payment.momo.vn/v2/gateway/api/create")
MOMO_REFUND_URL = os.getenv("MOMO_REFUND_URL", "https://test-payment.momo.vn/v2/gateway/api/refund")
MOMO_REFUND_QUERY_URL = os.getenv("MOMO_REFUND_QUERY_URL", "https://test-payment.momo.vn/v2/gateway/api/refund/query")
MOMO_REDIRECT_URL = os.getenv(
    "MOMO_REDIRECT_URL",
    f"{BACKEND_PUBLIC_URL}/api/momo/payment-return/" if BACKEND_PUBLIC_URL else "http://127.0.0.1:8000/api/momo/payment-return/",
)
MOMO_IPN_URL = os.getenv(
    "MOMO_IPN_URL",
    f"{BACKEND_PUBLIC_URL}/api/momo/ipn/" if BACKEND_PUBLIC_URL else "http://127.0.0.1:8000/api/momo/ipn/",
)
MOMO_STORE_ID = os.getenv("MOMO_STORE_ID", "MoMoTestStore")
MOMO_PARTNER_NAME = os.getenv("MOMO_PARTNER_NAME", "Course Platform Test")
LEARNING_PATH_PROVIDER = os.getenv("LEARNING_PATH_PROVIDER", "auto")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_TIMEOUT_SECONDS = int(os.getenv("GEMINI_TIMEOUT_SECONDS", "45"))
LEARNING_PATH_GEMINI_MAX_ATTEMPTS = max(1, int(os.getenv("LEARNING_PATH_GEMINI_MAX_ATTEMPTS", "1")))
LEARNING_PATH_GEMINI_CIRCUIT_THRESHOLD = max(1, int(os.getenv("LEARNING_PATH_GEMINI_CIRCUIT_THRESHOLD", "2")))
LEARNING_PATH_GEMINI_CIRCUIT_COOLDOWN_SECONDS = max(5, int(os.getenv("LEARNING_PATH_GEMINI_CIRCUIT_COOLDOWN_SECONDS", "60")))
LEARNING_PATH_FORCE_GEMINI = os.getenv("LEARNING_PATH_FORCE_GEMINI", "False") == "True"
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'corsheaders',
    'channels',
    'realtime',
    'activity_logs',

    'users',
    'rest_framework',
    'config',
    'courses',
    'instructors',
    'categories',
    'admins',
    'lessons',
    'coursemodules',
    'enrollments',
    'reviews',
    'learning_progress',
    'blog_posts',
    'lesson_attachments',
    'quiz_questions',
    'notifications',
    'promotions',
    'carts',
    'wishlists',
    'quiz_results',
    'qnas',
    'qna_answers',
    'forums',
    'forum_topics',
    'forum_comments',
    'systems_settings',
    'supports',
    'payments',
    'payment_details',
    'instructor_earnings',
    'instructor_payouts',
    'instructor_levels',
    'support_replies',
    'lesson_comments',
    'registration_forms',
    'applications',
    'certificates',
    'learning_paths',
    'subscription_plans',
    'payment_methods',
    'blog_comments',
    'search',
    'transcripts',
    'knowledge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'utils', 'mailer', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'




DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=30,
            ssl_require=True
        )
    }

    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update({
        "connect_timeout": 10,
    })

else:
    import sys
    if 'makemigrations' not in sys.argv and 'migrate' not in sys.argv and 'check' not in sys.argv:
        print("DATABASE_URL not set. Using SQLite.")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'payments.vnpay_services': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.momo_services': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}





LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True





STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (


    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {

        'anon': '200/min',
        'user': '600/min',


        'login': '50/min',
        'register': '30/min',
        'password_reset': '30/hour',
        'payment': '100/min',
        'quiz_submit': '50/min',
        'upload': '100/min',


        'review': '50/min',
        'support': '50/min',
        'notification': '300/min',


        'search': '300/min',


        'burst': '600/min',
    },
}


CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
]


FRONTEND_CORS = FRONTEND_URL
if FRONTEND_CORS and FRONTEND_CORS not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_CORS)
CORS_ALLOW_HEADERS = list(default_headers) + [
    'ngrok-skip-browser-warning',
]
CORS_ALLOW_CREDENTIALS = True


CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
if FRONTEND_CORS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_CORS)

TRANSCRIPT_LOCAL_WHISPER_MODEL = os.getenv("TRANSCRIPT_LOCAL_WHISPER_MODEL", "small")
TRANSCRIPT_LOCAL_WHISPER_DEVICE = os.getenv("TRANSCRIPT_LOCAL_WHISPER_DEVICE", "cpu")
TRANSCRIPT_LOCAL_WHISPER_COMPUTE_TYPE = os.getenv("TRANSCRIPT_LOCAL_WHISPER_COMPUTE_TYPE", "int8")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")
OPENAI_CHAT_MODEL = os.getenv("OPENAI_CHAT_MODEL", "gpt-4.1-mini")
KNOWLEDGE_MAX_CHUNKS_PER_REQUEST = int(os.getenv("KNOWLEDGE_MAX_CHUNKS_PER_REQUEST", "8"))
KNOWLEDGE_INCLUDE_DRAFTS_FOR_INSTRUCTOR = os.getenv("KNOWLEDGE_INCLUDE_DRAFTS_FOR_INSTRUCTOR", "true").lower() in ("1", "true", "yes")
