from django.contrib import admin
from django.urls import path, include
from config.seed_view import reset_db_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/reset-db/', reset_db_view, name='reset-db'),

    path('api/', include('users.urls')),
    path('api/', include('payments.urls')),

    path('api/', include('courses.urls')),
    path('api/', include('instructors.urls')),
    path('api/', include('categories.urls')),
    path('api/', include('admins.urls')),
    path('api/', include('lessons.urls')),
    path('api/', include('coursemodules.urls')),
    path('api/', include('enrollments.urls')),
    path('api/', include('learning_progress.urls')),
    path('api/', include('reviews.urls')),
    path('api/', include('blog_posts.urls')),
    path('api/', include('lesson_attachments.urls')),
    path('api/', include('quiz_questions.urls')),
    path('api/', include('notifications.urls')),
    path('api/', include('promotions.urls')),
    path('api/', include('carts.urls')),
    path('api/', include('wishlists.urls')),
    path('api/', include('quiz_results.urls')),
    path('api/', include('questions.urls')),
    path('api/', include('answers.urls')),
    path('api/', include('qa_votes.urls')),
    path('api/', include('systems_settings.urls')),
    path('api/', include('supports.urls')),
    path('api/', include('reports.urls')),
    path('api/', include('instructor_earnings.urls')),
    path('api/', include('instructor_payouts.urls')),
    path('api/', include('instructor_levels.urls')),
    path('api/', include('support_replies.urls')),
    path('api/', include('utils.upload.urls')),
    path('api/', include('lesson_comments.urls')),
    path('api/', include('registration_forms.urls')),
    path('api/', include('applications.urls')),
    path('api/', include('certificates.urls')),
    path('api/', include('learning_paths.urls')),
    path('api/', include('subscription_plans.urls')),
    path('api/', include('payment_methods.urls')),
    path('api/', include('activity_logs.urls')),
    path('api/', include('blog_comments.urls')),
    path('api/', include('realtime.urls')),
    path('api/', include('search.urls')),
    path('api/', include('transcripts.urls')),
    path('api/', include('newsletter.urls')),
]
