# Generated by Django 6.0.4 on 2026-05-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_blogpost_likes'),
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='last_report_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BlogBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_set', to='blog_posts.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_bookmarks', to='users.user')),
            ],
            options={
                'db_table': 'blog_bookmarks',
                'unique_together': {('user', 'blog_post')},
            },
        ),
    ]
