# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_blogpost_last_report_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
    ]
