# Generated by Django 6.0.4 on 2026-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0008_admin_actor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá cố định khi trả theo năm. Nếu đặt, sẽ ưu tiên hơn yearly_discount_percent.', max_digits=10, null=True),
        ),
    ]
