# Generated by Django 6.0.4 on 2026-06-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0009_subscriptionplan_yearly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='yearly_price',
        ),
    ]
