# Generated by Django 6.0.4 on 2026-06-13 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_options'),
        ('enrollments', '0013_enrollment_progress_denominator'),
        ('instructors', '0006_alter_instructor_options'),
        ('lessons', '0006_alter_lesson_content_type_add_code'),
        ('subscription_plans', '0012_alter_usersubscription_plan'),
        ('users', '0009_alter_refreshtoken_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionusage',
            name='consumed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubscriptionUsageEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_type', models.CharField(choices=[('video_progress', 'Video Progress'), ('lesson_complete', 'Lesson Complete'), ('manual', 'Manual')], default='video_progress', max_length=32)),
                ('delta_seconds', models.IntegerField(default=0)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform_commission_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instructor_share_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instructor_level_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('instructor_level_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage_events', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_usage_events', to='enrollments.enrollment')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_usage_events', to='instructors.instructor')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage_events', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage_events', to='users.user')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='subscription_plans.usersubscription')),
            ],
            options={
                'db_table': 'subscription_usage_events',
                'indexes': [models.Index(fields=['user_subscription', 'occurred_at'], name='subscriptio_user_su_1b0f3c_idx'), models.Index(fields=['course', 'occurred_at'], name='subscriptio_course__98ae21_idx'), models.Index(fields=['instructor', 'occurred_at'], name='subscriptio_instruc_e73eef_idx'), models.Index(fields=['lesson', 'user', 'occurred_at'], name='subscriptio_lesson__93fee2_idx')],
            },
        ),
    ]
