# Generated by Django 6.0.4 on 2026-06-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0004_delete_pathconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('advisor_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='learning_paths.learningpath')),
            ],
            options={
                'db_table': 'PathConversations',
            },
        ),
    ]
