# Generated by Django 6.0.4 on 2026-06-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0005_pathconversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PathConversation',
        ),
    ]
