# Generated by Django 5.2 on 2026-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_category_id_course_category_and_more'),
        ('instructor_earnings', '0005_rename_course_id_instructorearning_course_and_more'),
        ('instructor_payouts', '0005_rename_payout_id_instructorpayout_id_and_more'),
        ('instructors', '0005_rename_user_id_instructor_user'),
        ('payments', '0004_rename_payment_id_payment_id_and_more'),
        ('users', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instructorearning',
            name='InstructorE_instruc_709b79_idx',
        ),
        migrations.RemoveIndex(
            model_name='instructorearning',
            name='InstructorE_course__9ce49e_idx',
        ),
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['instructor'], name='InstructorE_instruc_709b79_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['course'], name='InstructorE_course__9ce49e_idx'),
        ),
    ]
