# Generated by Django 5.2 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_earnings', '0008_alter_instructorearning_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['instructor', 'is_deleted', 'earning_date'], name='InstructorEa_instru_6f71eb_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['instructor', 'is_deleted', 'status'], name='InstructorEa_instru_928722_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['is_deleted', 'earning_date'], name='InstructorEa_is_dele_7d5fd5_idx'),
        ),
    ]
