# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_earnings', '0010_rename_instructorea_instru_6f71eb_idx_instructore_instruc_ef07b6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorearning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instructor Earning', 'verbose_name_plural': 'Instructor Earnings'},
        ),
    ]
