# Generated by Django 6.0.4 on 2026-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_options'),
        ('instructor_earnings', '0011_alter_instructorearning_options'),
        ('instructor_payouts', '0005_rename_payout_id_instructorpayout_id_and_more'),
        ('instructors', '0006_alter_instructor_options'),
        ('payments', '0010_alter_payment_options'),
        ('subscription_plans', '0012_alter_usersubscription_plan'),
        ('users', '0009_alter_refreshtoken_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instructorearning',
            name='unique_earning_per_subscription_course_instructor',
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='earning_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='earning_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='instructor_level_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='instructor_level_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='instructor_share_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% giảng viên nhận tại thời điểm earning được tạo', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='platform_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% nền tảng giữ lại tại thời điểm earning được tạo', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='usage_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='usage_share_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='% usage của course/instructor trong kỳ subscription', max_digits=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='instructorearning',
            constraint=models.UniqueConstraint(condition=models.Q(('user_subscription__isnull', False)), fields=('user_subscription', 'course', 'instructor', 'earning_period_start'), name='unique_subscription_earning_per_period_course_instructor'),
        ),
    ]
