# Generated by Django 5.2 on 2026-02-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_rename_instructor_id_instructor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='user_id',
            new_name='user',
        ),
    ]
