# Generated by Django 5.2 on 2026-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_alter_instructor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
