# Generated by Django 5.2 on 2026-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_instructor_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='level_locked',
            field=models.BooleanField(default=False, help_text='Khi True, level do admin gán thủ công; job tự động nâng cấp sẽ bỏ qua giảng viên này.'),
        ),
    ]
