# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_alter_wishlist_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
    ]
