# Generated by Django 5.2 on 2026-02-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_lesson_id_lesson_id_and_more'),
        ('quiz_questions', '0002_quizquestion_deleted_at_quizquestion_deleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_lesson', to='lessons.lesson'),
        ),
    ]
