# Generated by Django 6.0.4 on 2026-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0005_quizquestion_allowed_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='function_name',
            field=models.CharField(blank=True, default='', help_text='Function name students must implement', max_length=100),
        ),
    ]
