# Generated by Django 6.0.4 on 2026-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0006_quizquestion_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='require_completion',
            field=models.BooleanField(default=False, help_text='If True, student must pass 100% of test cases. If False, quiz passing score threshold applies.'),
        ),
    ]
