# Generated by Django 6.0.4 on 2026-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0007_add_require_completion_to_quizquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['-created_at']},
        ),
    ]
